//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Files struct {
	ID        int64 `sql:"primary_key"`
	OwnerID   int64
	FolderID  *int64
	Name      string
	SizeBytes int64
	Extension *string
	MimeType  string
	TrashedAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}
