//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ContactGroup = newContactGroupTable("public", "contact_group", "")

type contactGroupTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	OwnerID   postgres.ColumnString
	Name      postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ContactGroupTable struct {
	contactGroupTable

	EXCLUDED contactGroupTable
}

// AS creates new ContactGroupTable with assigned alias
func (a ContactGroupTable) AS(alias string) *ContactGroupTable {
	return newContactGroupTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ContactGroupTable with assigned schema name
func (a ContactGroupTable) FromSchema(schemaName string) *ContactGroupTable {
	return newContactGroupTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ContactGroupTable with assigned table prefix
func (a ContactGroupTable) WithPrefix(prefix string) *ContactGroupTable {
	return newContactGroupTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ContactGroupTable with assigned table suffix
func (a ContactGroupTable) WithSuffix(suffix string) *ContactGroupTable {
	return newContactGroupTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newContactGroupTable(schemaName, tableName, alias string) *ContactGroupTable {
	return &ContactGroupTable{
		contactGroupTable: newContactGroupTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newContactGroupTableImpl("", "excluded", ""),
	}
}

func newContactGroupTableImpl(schemaName, tableName, alias string) contactGroupTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		OwnerIDColumn   = postgres.StringColumn("owner_id")
		NameColumn      = postgres.StringColumn("name")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, OwnerIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{OwnerIDColumn, NameColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return contactGroupTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		OwnerID:   OwnerIDColumn,
		Name:      NameColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
