//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UploadSession = newUploadSessionTable("public", "upload_session", "")

type uploadSessionTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	OwnerID        postgres.ColumnString
	FileName       postgres.ColumnString
	FileSize       postgres.ColumnInteger
	MimeType       postgres.ColumnString
	FolderID       postgres.ColumnString
	TotalChunks    postgres.ColumnInteger
	QuotaAllocated postgres.ColumnInteger
	UploadedBytes  postgres.ColumnInteger
	CreatedAt      postgres.ColumnTimestamp
	ExpiresAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UploadSessionTable struct {
	uploadSessionTable

	EXCLUDED uploadSessionTable
}

// AS creates new UploadSessionTable with assigned alias
func (a UploadSessionTable) AS(alias string) *UploadSessionTable {
	return newUploadSessionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UploadSessionTable with assigned schema name
func (a UploadSessionTable) FromSchema(schemaName string) *UploadSessionTable {
	return newUploadSessionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UploadSessionTable with assigned table prefix
func (a UploadSessionTable) WithPrefix(prefix string) *UploadSessionTable {
	return newUploadSessionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UploadSessionTable with assigned table suffix
func (a UploadSessionTable) WithSuffix(suffix string) *UploadSessionTable {
	return newUploadSessionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUploadSessionTable(schemaName, tableName, alias string) *UploadSessionTable {
	return &UploadSessionTable{
		uploadSessionTable: newUploadSessionTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newUploadSessionTableImpl("", "excluded", ""),
	}
}

func newUploadSessionTableImpl(schemaName, tableName, alias string) uploadSessionTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		OwnerIDColumn        = postgres.StringColumn("owner_id")
		FileNameColumn       = postgres.StringColumn("file_name")
		FileSizeColumn       = postgres.IntegerColumn("file_size")
		MimeTypeColumn       = postgres.StringColumn("mime_type")
		FolderIDColumn       = postgres.StringColumn("folder_id")
		TotalChunksColumn    = postgres.IntegerColumn("total_chunks")
		QuotaAllocatedColumn = postgres.IntegerColumn("quota_allocated")
		UploadedBytesColumn  = postgres.IntegerColumn("uploaded_bytes")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		ExpiresAtColumn      = postgres.TimestampColumn("expires_at")
		allColumns           = postgres.ColumnList{IDColumn, OwnerIDColumn, FileNameColumn, FileSizeColumn, MimeTypeColumn, FolderIDColumn, TotalChunksColumn, QuotaAllocatedColumn, UploadedBytesColumn, CreatedAtColumn, ExpiresAtColumn}
		mutableColumns       = postgres.ColumnList{OwnerIDColumn, FileNameColumn, FileSizeColumn, MimeTypeColumn, FolderIDColumn, TotalChunksColumn, QuotaAllocatedColumn, UploadedBytesColumn, CreatedAtColumn, ExpiresAtColumn}
		defaultColumns       = postgres.ColumnList{UploadedBytesColumn, CreatedAtColumn}
	)

	return uploadSessionTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		OwnerID:        OwnerIDColumn,
		FileName:       FileNameColumn,
		FileSize:       FileSizeColumn,
		MimeType:       MimeTypeColumn,
		FolderID:       FolderIDColumn,
		TotalChunks:    TotalChunksColumn,
		QuotaAllocated: QuotaAllocatedColumn,
		UploadedBytes:  UploadedBytesColumn,
		CreatedAt:      CreatedAtColumn,
		ExpiresAt:      ExpiresAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
