//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Files struct {
	ID            uuid.UUID `sql:"primary_key"`
	UserID        uuid.UUID
	FolderID      *uuid.UUID
	Name          string
	FileSizeBytes int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
}
