//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Shares struct {
	ID          uuid.UUID `sql:"primary_key"`
	OwnerID     uuid.UUID
	RecipientID *uuid.UUID
	FolderID    *uuid.UUID
	FileID      *uuid.UUID
	Permission  string
	SharedAt    time.Time
	SharedUntil *time.Time
}
