//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Auths = newAuthsTable("public", "auths", "")

type authsTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnInteger
	ProfileID      postgres.ColumnInteger
	Provider       postgres.ColumnString
	ProviderUserID postgres.ColumnString
	PasswordHash   postgres.ColumnString
	CreatedAt      postgres.ColumnTimestamp
	UpdatedAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AuthsTable struct {
	authsTable

	EXCLUDED authsTable
}

// AS creates new AuthsTable with assigned alias
func (a AuthsTable) AS(alias string) *AuthsTable {
	return newAuthsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AuthsTable with assigned schema name
func (a AuthsTable) FromSchema(schemaName string) *AuthsTable {
	return newAuthsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AuthsTable with assigned table prefix
func (a AuthsTable) WithPrefix(prefix string) *AuthsTable {
	return newAuthsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AuthsTable with assigned table suffix
func (a AuthsTable) WithSuffix(suffix string) *AuthsTable {
	return newAuthsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAuthsTable(schemaName, tableName, alias string) *AuthsTable {
	return &AuthsTable{
		authsTable: newAuthsTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newAuthsTableImpl("", "excluded", ""),
	}
}

func newAuthsTableImpl(schemaName, tableName, alias string) authsTable {
	var (
		IDColumn             = postgres.IntegerColumn("id")
		ProfileIDColumn      = postgres.IntegerColumn("profile_id")
		ProviderColumn       = postgres.StringColumn("provider")
		ProviderUserIDColumn = postgres.StringColumn("provider_user_id")
		PasswordHashColumn   = postgres.StringColumn("password_hash")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampColumn("updated_at")
		allColumns           = postgres.ColumnList{IDColumn, ProfileIDColumn, ProviderColumn, ProviderUserIDColumn, PasswordHashColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns       = postgres.ColumnList{ProfileIDColumn, ProviderColumn, ProviderUserIDColumn, PasswordHashColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return authsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		ProfileID:      ProfileIDColumn,
		Provider:       ProviderColumn,
		ProviderUserID: ProviderUserIDColumn,
		PasswordHash:   PasswordHashColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
