//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Files = newFilesTable("public", "files", "")

type filesTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	OwnerID   postgres.ColumnInteger
	FolderID  postgres.ColumnInteger
	Name      postgres.ColumnString
	SizeBytes postgres.ColumnInteger
	Extension postgres.ColumnString
	MimeType  postgres.ColumnString
	TrashedAt postgres.ColumnTimestamp
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type FilesTable struct {
	filesTable

	EXCLUDED filesTable
}

// AS creates new FilesTable with assigned alias
func (a FilesTable) AS(alias string) *FilesTable {
	return newFilesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FilesTable with assigned schema name
func (a FilesTable) FromSchema(schemaName string) *FilesTable {
	return newFilesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FilesTable with assigned table prefix
func (a FilesTable) WithPrefix(prefix string) *FilesTable {
	return newFilesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FilesTable with assigned table suffix
func (a FilesTable) WithSuffix(suffix string) *FilesTable {
	return newFilesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFilesTable(schemaName, tableName, alias string) *FilesTable {
	return &FilesTable{
		filesTable: newFilesTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newFilesTableImpl("", "excluded", ""),
	}
}

func newFilesTableImpl(schemaName, tableName, alias string) filesTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		OwnerIDColumn   = postgres.IntegerColumn("owner_id")
		FolderIDColumn  = postgres.IntegerColumn("folder_id")
		NameColumn      = postgres.StringColumn("name")
		SizeBytesColumn = postgres.IntegerColumn("size_bytes")
		ExtensionColumn = postgres.StringColumn("extension")
		MimeTypeColumn  = postgres.StringColumn("mime_type")
		TrashedAtColumn = postgres.TimestampColumn("trashed_at")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, OwnerIDColumn, FolderIDColumn, NameColumn, SizeBytesColumn, ExtensionColumn, MimeTypeColumn, TrashedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{OwnerIDColumn, FolderIDColumn, NameColumn, SizeBytesColumn, ExtensionColumn, MimeTypeColumn, TrashedAtColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return filesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		OwnerID:   OwnerIDColumn,
		FolderID:  FolderIDColumn,
		Name:      NameColumn,
		SizeBytes: SizeBytesColumn,
		Extension: ExtensionColumn,
		MimeType:  MimeTypeColumn,
		TrashedAt: TrashedAtColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
