//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Contact struct {
	ID        int64 `sql:"primary_key"`
	OwnerID   int64
	Email     string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
