//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type FileInfo struct {
	ID        uuid.UUID `sql:"primary_key"`
	OwnerID   uuid.UUID
	FolderID  *uuid.UUID
	Name      string
	Size      int64
	Extension *string
	MimeType  string
	Category  *string
	Preview   *[]byte
	TrashedAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}
