//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FileInfo struct {
	ID            int64 `sql:"primary_key"`
	OwnerID       int64
	FolderID      *int64
	Name          string
	GeneratedName string
	Size          int64
	Extension     *string
	MimeType      string
	Category      *string
	Preview       *[]byte
	TrashedAt     *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
