//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FolderInfo struct {
	ID             int64 `sql:"primary_key"`
	OwnerID        int64
	Name           string
	ParentFolderID *int64
	TrashedAt      *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
