//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Profile struct {
	ID                uuid.UUID `sql:"primary_key"`
	Email             string
	FullName          string
	Avatar            *[]byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
	StorageQuotaBytes int64
	StorageUsedBytes  int64
}
