//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ShareRecipient struct {
	ID             int64 `sql:"primary_key"`
	ShareConfigID  int64
	ContactID      *int64
	GroupID        *int64
	Email          *string
	DownloadsCount int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
