//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ShareConfig struct {
	ID           int64 `sql:"primary_key"`
	CustomID     uuid.UUID
	OwnerID      int64
	FileID       *int64
	FolderID     *int64
	PasswordHash *string
	MaxDownloads *int64
	ExpiresAt    *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
