//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UploadSession struct {
	ID             uuid.UUID `sql:"primary_key"`
	OwnerID        uuid.UUID
	FileName       string
	FileSize       int64
	MimeType       string
	FolderID       *uuid.UUID
	TotalChunks    int32
	QuotaAllocated int64
	UploadedBytes  int64
	CreatedAt      time.Time
	ExpiresAt      time.Time
}
