name: skyvault
services:
  skyvault-db:
    container_name: ${DB__CONTAINER__NAME}
    image: ${DB__CONTAINER__IMAGE}
    restart: always
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASS}
      POSTGRES_DB: ${DB__NAME}
    volumes:
      - ${DB__HOST__VOLUME}:/var/lib/postgresql/data
    ports:
      - "${DB__HOST__PORT}:${DB__CONTAINER__PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB__NAME} -U ${DB__USER}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
