//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Profiles struct {
	ID        int64 `sql:"primary_key"`
	Email     string
	FullName  string
	Avatar    *[]byte
	CreatedAt time.Time
	UpdatedAt time.Time
}
