//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Files = newFilesTable("public", "files", "")

type filesTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnString
	UserID        postgres.ColumnString
	FolderID      postgres.ColumnString
	Name          postgres.ColumnString
	FileSizeBytes postgres.ColumnInteger
	CreatedAt     postgres.ColumnTimestamp
	UpdatedAt     postgres.ColumnTimestamp
	DeletedAt     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type FilesTable struct {
	filesTable

	EXCLUDED filesTable
}

// AS creates new FilesTable with assigned alias
func (a FilesTable) AS(alias string) *FilesTable {
	return newFilesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FilesTable with assigned schema name
func (a FilesTable) FromSchema(schemaName string) *FilesTable {
	return newFilesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FilesTable with assigned table prefix
func (a FilesTable) WithPrefix(prefix string) *FilesTable {
	return newFilesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FilesTable with assigned table suffix
func (a FilesTable) WithSuffix(suffix string) *FilesTable {
	return newFilesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFilesTable(schemaName, tableName, alias string) *FilesTable {
	return &FilesTable{
		filesTable: newFilesTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newFilesTableImpl("", "excluded", ""),
	}
}

func newFilesTableImpl(schemaName, tableName, alias string) filesTable {
	var (
		IDColumn            = postgres.StringColumn("id")
		UserIDColumn        = postgres.StringColumn("user_id")
		FolderIDColumn      = postgres.StringColumn("folder_id")
		NameColumn          = postgres.StringColumn("name")
		FileSizeBytesColumn = postgres.IntegerColumn("file_size_bytes")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		UpdatedAtColumn     = postgres.TimestampColumn("updated_at")
		DeletedAtColumn     = postgres.TimestampColumn("deleted_at")
		allColumns          = postgres.ColumnList{IDColumn, UserIDColumn, FolderIDColumn, NameColumn, FileSizeBytesColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		mutableColumns      = postgres.ColumnList{UserIDColumn, FolderIDColumn, NameColumn, FileSizeBytesColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
	)

	return filesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		UserID:        UserIDColumn,
		FolderID:      FolderIDColumn,
		Name:          NameColumn,
		FileSizeBytes: FileSizeBytesColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,
		DeletedAt:     DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
