//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Shares = newSharesTable("public", "shares", "")

type sharesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	OwnerID     postgres.ColumnString
	RecipientID postgres.ColumnString
	FolderID    postgres.ColumnString
	FileID      postgres.ColumnString
	Permission  postgres.ColumnString
	SharedAt    postgres.ColumnTimestamp
	SharedUntil postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SharesTable struct {
	sharesTable

	EXCLUDED sharesTable
}

// AS creates new SharesTable with assigned alias
func (a SharesTable) AS(alias string) *SharesTable {
	return newSharesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SharesTable with assigned schema name
func (a SharesTable) FromSchema(schemaName string) *SharesTable {
	return newSharesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SharesTable with assigned table prefix
func (a SharesTable) WithPrefix(prefix string) *SharesTable {
	return newSharesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SharesTable with assigned table suffix
func (a SharesTable) WithSuffix(suffix string) *SharesTable {
	return newSharesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSharesTable(schemaName, tableName, alias string) *SharesTable {
	return &SharesTable{
		sharesTable: newSharesTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newSharesTableImpl("", "excluded", ""),
	}
}

func newSharesTableImpl(schemaName, tableName, alias string) sharesTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		OwnerIDColumn     = postgres.StringColumn("owner_id")
		RecipientIDColumn = postgres.StringColumn("recipient_id")
		FolderIDColumn    = postgres.StringColumn("folder_id")
		FileIDColumn      = postgres.StringColumn("file_id")
		PermissionColumn  = postgres.StringColumn("permission")
		SharedAtColumn    = postgres.TimestampColumn("shared_at")
		SharedUntilColumn = postgres.TimestampColumn("shared_until")
		allColumns        = postgres.ColumnList{IDColumn, OwnerIDColumn, RecipientIDColumn, FolderIDColumn, FileIDColumn, PermissionColumn, SharedAtColumn, SharedUntilColumn}
		mutableColumns    = postgres.ColumnList{OwnerIDColumn, RecipientIDColumn, FolderIDColumn, FileIDColumn, PermissionColumn, SharedAtColumn, SharedUntilColumn}
	)

	return sharesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		OwnerID:     OwnerIDColumn,
		RecipientID: RecipientIDColumn,
		FolderID:    FolderIDColumn,
		FileID:      FileIDColumn,
		Permission:  PermissionColumn,
		SharedAt:    SharedAtColumn,
		SharedUntil: SharedUntilColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
